### PR TITLE
added mouse over function and sample-1.html

### PR DESCRIPTION
**Pull request by baladkb**
Hi @smurfy,
Sorry for delay,
I added the sample-1.html and updated the cloud-zoom.js, please check...

### CODE REVIEW

**Comment by smurfy** [comment]
Thanks, some stuff i don't like: (just looked at the code, but i can fix too)
* its not optional
* "click" and "mouseover" code is the same, would make sense to create a var method = function().. and use it for both events. (again mouseover thing optional)

**Comment by baladkb** [comment]
Ok @smurfy, 
For your reference : sample-1.html use full for users please check ...

**Comment by baladkb** [comment]
can I give separate pull request for [sample-1.html](https://github.com/baladkb/cloud-zoom/blob/master/sample-1.html) page.

**Comment by smurfy** [comment]
Just update this one if you have something new. I will look at this later today.

**Comment by baladkb** [comment]
Ok thanks @smurfy.
I'll give PR for sample-1.html.

**Comment by baladkb** [comment]
@smurfy have You checked the [PR](https://github.com/smurfy/cloud-zoom/pull/10/commits/9194867e0d0d461aae37bca4f24310f2eaa573f2)?

**Pull request merged**
